name: CI

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  other:
    name: Test ${{ matrix.platform }} (${{ matrix.go }})
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18.x"]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build for ${{ matrix.platform }}
        run: go build ./...
      - name: Test
        run: go test -v ./...
